services:

  backend:
    build: ./back
    image: ${CI_REGISTRY_BACKEND}/${IMAGE_TAG}
    ports:
      - "8080:8080"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
