version: "3.7"

services:
  db:
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    ports:
      - ${LOCAL_DB_PORT:-15432}:5432
    volumes:
      - ./${POSTGRES_DATA:-postgres-data}:/var/lib/postgresql/data:cached
    env_file:
      - back/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data:cached"

  backend:
    command: uvicorn src.main:app --reload
    env_file:
      - back/.env
    volumes:
      - ./back:/back:cached
#    entrypoint: wait-for -t ${WAIT_FOR_TIMEOUT:-20} db:5432 -- /back/entrypoint.sh
    build:
      context: ./back
    expose: [2000,8000]
    ports:
      - ${LOCAL_BACKEND_PORT:-8000}:8000
