version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./back/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./back/Dockerfile
    env_file:
      - ./back/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
