name: Deploy Docker Stack

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: echo ${{ vars.REMOTE_HOST }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          echo $CI_REGISTRY_BACKEND
          echo $IMAGE_TAG
          docker compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CR_REGISTRY }}
          username: ${{ secrets.CR_KEY_ID }}
          password: ${{ secrets.CR_KEY_PASS }}

      - name: Push Docker images
        run: docker compose push

  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ vars.REPO_NAME }}:${{ github.sha }}
      CI_REGISTRY_BACKEND: ${{ vars.CR_REGISTRY }}
    needs: build
    steps:
      - name: Create SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./id_rsa
          chmod 600 ./id_rsa

      - name: Add Remote Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Docker Stack
        uses: kitconcept/docker-stack-deploy@v1.0.1
        with:
          registry: ${{ vars.CR_REGISTRY }}
          username: ${{ secrets.CR_KEY_ID }}
          password: ${{ secrets.CR_KEY_PASS }}
          remote_host: ${{ vars.REMOTE_HOST }}
          remote_user: ${{ vars.REMOTE_USER }}
          remote_private_key: cat ./id_rsa
          stack_file: "docker-compose.yml"
          stack_name: "square_planner"
