name: Deploy Docker Stack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./id_rsa
          chmod 600 ./id_rsa

      - name: Add Remote Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Build Docker images
        run: docker compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CR_REGISTRY }}
          username: ${{ secrets.CR_KEY_ID }}
          password: ${{ secrets.CR_KEY_PASS }}

      - name: Push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{env.REPO_NAME}}:${{github.head_ref}}

      - name: Deploy
        uses: kitconcept/docker-stack-deploy@v1.0.1
        with:
            registry: ${{ secrets.CR_REGISTRY }}
            username: ${{ secrets.CR_KEY_ID }}
            password: ${{ secrets.CR_KEY_PASS }}
            remote_host: ${{ secrets.REMOTE_HOST }}
            remote_user: ${{ secrets.REMOTE_USER }}
            remote_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
            stack_file: "docker-compose.yml"
            stack_name: "sq"
            stack_param: "sq"



#      - name: Deploy Docker Stack on Remote Server
#        run: |
#          ssh -i ./id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
#            docker stack deploy -c /path/to/your/docker-compose.yml your_stack_name
#          EOF
