name: Node CI

on:
  push:
    branches:
      - master  # Запуск при пуше в ветку master
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker-compose build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "."  # Укажите путь к вашему docker-compose.yml
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}  # Директория на сервере
          EXCLUDE: ""

      - name: Run Docker containers on Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd ${{ secrets.REMOTE_TARGET }}  # Путь к вашему приложению на сервере
            docker-compose up -d  # Запустите контейнеры
          EOF
