name: test_ssh

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH Command
        run: |
          RESULT=$(ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} ls)
          echo "Результат выполнения команды:"
          echo "$RESULT"
