name: test_ssh

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ vars.REPO_NAME }}:${{ github.sha }}
      CI_REGISTRY_BACKEND: ${{ vars.CR_REGISTRY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./id_rsa
          chmod 600 ./id_rsa

      - name: Add Remote Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Copy docker-compose.yml to Remote Host
        run: |
          scp -i ./id_rsa -o StrictHostKeyChecking=no docker-compose.yml ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }}:/home/${{ vars.REMOTE_USER }}/docker-compose.yml

      - name: Deploy Docker Stack
        run: |
          ssh -i ./id_rsa -o StrictHostKeyChecking=no ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }}
          export IMAGE_TAG='${{ env.IMAGE_TAG }}'
          export CI_REGISTRY_BACKEND='${{ env.CI_REGISTRY_BACKEND }}'
          docker stack deploy -c docker-compose.yml --with-registry-auth --resolve-image=always square_planner
